### ISSUE TITLE
4 channel HDAWG

### ISSUE THREAD

**Issue by MatthewGreen1** [zhinst/zhinst-toolkit#89]
The HDAWG driver attempts to initialise 4 awg cores when on a 4 channel instrument only 2 exist. The error is

```
from zhinst.toolkit.control.drivers.hdawg import HDAWG
hdawg=HDAWG('hdawg', 'DEV8162', interface='USB', host='localhost')
hdawg.setup()
hdawg.connect_device()

Successfully connected to data server at localhost:8004 api version: 6
Successfully connected to device DEV8162 on interface USB
ERROR:
The device hdawg (dev8162) does not have the node /dev8162/awgs/2/enable. Please check the node address.

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\hdawg.py", line 112, in connect_device
    self._init_awg_cores()

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\hdawg.py", line 170, in _init_awg_cores
    [awg._init_awg_params() for awg in self.awgs]

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\hdawg.py", line 170, in <listcomp>
    [awg._init_awg_params() for awg in self.awgs]

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\hdawg.py", line 329, in _init_awg_params
    self._parent._get_node_dict(f"awgs/{self._index}/enable"),

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\base\base.py", line 501, in _get_node_dict
    self._check_node_exists(device_node)

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\control\drivers\base\base.py", line 546, in _check_node_exists
    _logger.ExceptionTypes.ToolkitError,

  File "C:\Users\ultservi\.conda\envs\qcodes\lib\site-packages\zhinst\toolkit\interface\interface.py", line 192, in error
    raise LoggerModule.ToolkitError(msg)

zhinst.toolkit.interface.interface.ToolkitError: The device hdawg (dev8162) does not have the node /dev8162/awgs/2/enable. Please check the node address.
```

A quick fix for this is to change the number in  ```_init_awg_cores```  from 4 to 2, but is there a more permanent solution that won't require editing the driver with each update?

```
def _init_awg_cores(self):
    """Initialize the AWGs cores of the device."""
    self._awgs = [AWG(self, i) for i in range(4)] # Change to 2
    [awg._setup() for awg in self.awgs]
    [awg._init_awg_params() for awg in self.awgs]
    [awg._init_ct() for awg in self.awgs]
```

**Comment by tobiasah** [comment]
Thanks for reporting this. I agree this can and should be done automatically.
For the new instruments we support this already, as far as I know.
I will take a look into it and keep you updated.
